### ISSUE TITLE
il faudrait indiquer la dépendance à l'extension dans le composer.json

### ISSUE THREAD

**Issue by omansour** [M6Web/CassandraBundle#2]
afin d'éviter les déploiements foireux 

https://github.com/datastax/php-driver/blob/master/ext/README.md

**Comment by t-geindre** [comment]
Dans le composer.json on a la dépendance vers `"datastax/php-driver": "dev-master"` (à fixer sur une version stable d'ailleurs), qui dépend elle même de `"ext-cassandra": "*"`. Il me semble que c'est suffisant non ?

**Comment by omansour** [comment]
anafé :)

**Comment by mguillermin** [comment]
Pour info, il n'y a pas de version stable de "datastax/php-driver" pour l'instant. La seule version tagguée (une alpha) est bugée. On doit donc rester sur "dev-master" pour l'instant.

**Comment by t-geindre** [comment]
@mguillermin ok c'est noté. Par contre, est-ce qu'on pourrait pas passer le `minimum-stability` en `stable` et forcer le `@dev` sur la dépendance au driver ?
