### ISSUE TITLE
Symfony 4: Compatibility

### ISSUE THREAD

**Issue by PierreLeMaguer** [M6Web/CassandraBundle#34]
Hello.
I noticed a compatibility problem with Symfony 4. Indeed, a new method reset() appeared for the interface Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface .
Here, the commit: 
[https://github.com/symfony/http-kernel/commit/afee8cb4d7d4263022d26493048ef4ab00db753c#diff-fafaa73029c93472d7a69e7c75c11cc7](https://github.com/symfony/http-kernel/commit/afee8cb4d7d4263022d26493048ef4ab00db753c#diff-fafaa73029c93472d7a69e7c75c11cc7)
So, it causes an error because of the class M6Web\Bundle\CassandraBundle\DataCollector\CassandraDataCollector . Add a method to this class fixes the problem.
For example:
`
    /**
     * {@inheritdoc}
     */
    public function reset()
    {
        $this->data['cassandra'] = new \SplQueue();
    }
`
Thanks.

**Comment by gbouyge** [comment]
Thank you Pierre,
We are progresivly moving our repositories to symfony 4.

Feel free to create a pull request if you have a chance. We will look at it. 

Thank you !

**Comment by Oliboy50** [comment]
@PierreLeMaguer 

Could you confirm that [this PR](https://github.com/M6Web/CassandraBundle/pull/35) works for you, please?

Thanks

**Comment by PierreLeMaguer** [comment]
It works for me :)

**Comment by Oliboy50** [comment]
@PierreLeMaguer done in `v2.2.1`
