### ISSUE TITLE
Symfony 4.2 service is private

### ISSUE THREAD

**Issue by tijnhendrikson** [M6Web/CassandraBundle#37]
Symfony 4 can't load the service, since all services are set to private by default.

This can be fixed by  setting the service to public inside the M6WebCassandraExtension class.
_Notice: $definition->setPublic(true);_

```php
protected function loadClient(ContainerBuilder $container, $clientId, array $config)
{
    $class = 'M6Web\Bundle\CassandraBundle\Cassandra\Client';
    $definition = new Definition($class);
    $definition->addArgument($config);
    $definition->setConfigurator(['M6Web\Bundle\CassandraBundle\Cassandra\Configurator', 'buildCluster']);

    // set service to public
    $definition->setPublic(true);

    if ($config['dispatch_events']) {
        $definition->addMethodCall('setEventDispatcher', [new Reference('event_dispatcher')]);
    }

    $container->setDefinition('m6web_cassandra.client.'.$clientId, $definition);
}
```

**Comment by Oliboy50** [comment]
Hello @liacmedia, thanks for pointing this.

You are completely right and we would be happy to merge your pull request if you want to fix this :)

**Comment by gbouyge** [comment]
Fix in https://github.com/M6Web/CassandraBundle/releases/tag/v2.2.2
Thanks again @liacmedia for the pull request 👍
