### ISSUE TITLE
PHP 56 compatibility

### ISSUE THREAD

**Issue by woqs** [M6Web/CassandraBundle#40]
Hi,

From version 2.1.0 you are telling on `composer.json` that your library is compatible with php 5.6 or above.

You're using the ?? in `CassandraDataCollector` though, making it 7.0 or above compliant.

Could you change this, by making a version compatible with 56 (like isset($a['a'])? $a['a'] : '';), and another one with the composer.json modified?

Thanks

**Comment by omansour** [comment]
thanks for the contribution

as PHP 5.6 is no more supported, I think I will update the requirement in the composer.json to php 7.2

**Comment by woqs** [comment]
Thanks!

Have a nice day
