### ISSUE TITLE
No possibility to create a PR for a previous version

### ISSUE THREAD

**Issue by woqs** [M6Web/CassandraBundle#41]
Hi,

I'd like to add a version after the 1.1.2, to be able to use the datastax versions 1.2 and 1.3.

As there is no branch linked to this version I can't create this PR.

Is it possible to create it?

Thanks

**Comment by fabdsp** [comment]
Hello,

Here is the branch : https://github.com/M6Web/CassandraBundle/tree/1.1

Thank you !
Fabien
